sudo: required

language: python3

services:
  - docker

jobs:
  include:
    - stage: lint
      script: docker-compose run web flake8
    - stage: test
      script: docker-compose run web pytest -v
    - stage: release
      rvm: 2.3
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
