sudo: required

language: python3

services:
  - docker

jobs:
  include:
    - stage: lint
      script: docker-compose run web flake8
    - stage: test
      script: docker-compose run web pytest -v
