version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:9898
    volumes:
      - .:/code
    ports:
      - "9898:9898"
    depends_on:
      - db
